#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 148
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 100
#define ALIAS_COUNT 0
#define TOKEN_COUNT 55
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_BQUOTE = 1,
  anon_sym_COMMA = 2,
  anon_sym_SLASH = 3,
  anon_sym_h = 4,
  anon_sym_STAR = 5,
  anon_sym_DASH = 6,
  anon_sym_CARET = 7,
  anon_sym_GT = 8,
  anon_sym_LT = 9,
  anon_sym_v = 10,
  anon_sym_p = 11,
  anon_sym_q = 12,
  anon_sym_s = 13,
  anon_sym_z = 14,
  anon_sym_pp = 15,
  anon_sym_qq = 16,
  anon_sym_V = 17,
  anon_sym_w = 18,
  sym_setBreak = 19,
  sym_setEx = 20,
  sym_setFirework = 21,
  anon_sym_DOLLAR_DOLLAR = 22,
  anon_sym_DOLLAR = 23,
  sym_setFakeTap = 24,
  anon_sym_QMARK = 25,
  anon_sym_BANG = 26,
  anon_sym_LBRACK = 27,
  anon_sym_POUND = 28,
  anon_sym_RBRACK = 29,
  anon_sym_POUND_POUND = 30,
  anon_sym_COLON = 31,
  anon_sym_A = 32,
  anon_sym_B = 33,
  anon_sym_D = 34,
  anon_sym_E = 35,
  anon_sym_C = 36,
  anon_sym_C1 = 37,
  anon_sym_C2 = 38,
  sym__position = 39,
  anon_sym_LPAREN = 40,
  anon_sym_RPAREN = 41,
  anon_sym_LBRACE = 42,
  anon_sym_RBRACE = 43,
  anon_sym_DOT = 44,
  anon_sym_0 = 45,
  anon_sym_1 = 46,
  anon_sym_2 = 47,
  anon_sym_3 = 48,
  anon_sym_4 = 49,
  anon_sym_5 = 50,
  anon_sym_6 = 51,
  anon_sym_7 = 52,
  anon_sym_8 = 53,
  anon_sym_9 = 54,
  sym_inote = 55,
  sym_division = 56,
  sym_pseudo = 57,
  sym__note = 58,
  sym_taps = 59,
  sym_tap = 60,
  sym_hold = 61,
  sym_slides = 62,
  sym_slide = 63,
  sym_touch = 64,
  sym_touchHold = 65,
  sym_shape = 66,
  sym_decorationTap = 67,
  sym_decorationHold = 68,
  sym_decorationStar = 69,
  sym_decorationSlide = 70,
  sym_decorationTouch = 71,
  sym_setFakeStar = 72,
  sym_setNoStar = 73,
  sym_duration = 74,
  sym_durationDelay = 75,
  sym_measure = 76,
  sym_length = 77,
  sym__button = 78,
  sym__sensor = 79,
  sym_setBpm = 80,
  sym_setDenominator = 81,
  sym_bpm = 82,
  sym__denominator = 83,
  aux_sym__num = 84,
  sym__decimal = 85,
  sym__digit = 86,
  sym_end = 87,
  aux_sym_inote_repeat1 = 88,
  aux_sym_division_repeat1 = 89,
  aux_sym_pseudo_repeat1 = 90,
  aux_sym_taps_repeat1 = 91,
  aux_sym_tap_repeat1 = 92,
  aux_sym_hold_repeat1 = 93,
  aux_sym_slides_repeat1 = 94,
  aux_sym_slides_repeat2 = 95,
  aux_sym_slide_repeat1 = 96,
  aux_sym_slide_repeat2 = 97,
  aux_sym_touchHold_repeat1 = 98,
  aux_sym__decimal_repeat1 = 99,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_COMMA] = ",",
  [anon_sym_SLASH] = "/",
  [anon_sym_h] = "h",
  [anon_sym_STAR] = "*",
  [anon_sym_DASH] = "-",
  [anon_sym_CARET] = "^",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_v] = "v",
  [anon_sym_p] = "p",
  [anon_sym_q] = "q",
  [anon_sym_s] = "s",
  [anon_sym_z] = "z",
  [anon_sym_pp] = "pp",
  [anon_sym_qq] = "qq",
  [anon_sym_V] = "V",
  [anon_sym_w] = "w",
  [sym_setBreak] = "setBreak",
  [sym_setEx] = "setEx",
  [sym_setFirework] = "setFirework",
  [anon_sym_DOLLAR_DOLLAR] = "$$",
  [anon_sym_DOLLAR] = "$",
  [sym_setFakeTap] = "setFakeTap",
  [anon_sym_QMARK] = "\?",
  [anon_sym_BANG] = "!",
  [anon_sym_LBRACK] = "[",
  [anon_sym_POUND] = "#",
  [anon_sym_RBRACK] = "]",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_COLON] = ":",
  [anon_sym_A] = "A",
  [anon_sym_B] = "B",
  [anon_sym_D] = "D",
  [anon_sym_E] = "E",
  [anon_sym_C] = "C",
  [anon_sym_C1] = "C1",
  [anon_sym_C2] = "C2",
  [sym__position] = "_position",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOT] = ".",
  [anon_sym_0] = "0",
  [anon_sym_1] = "1",
  [anon_sym_2] = "2",
  [anon_sym_3] = "3",
  [anon_sym_4] = "4",
  [anon_sym_5] = "5",
  [anon_sym_6] = "6",
  [anon_sym_7] = "7",
  [anon_sym_8] = "8",
  [anon_sym_9] = "9",
  [sym_inote] = "inote",
  [sym_division] = "division",
  [sym_pseudo] = "pseudo",
  [sym__note] = "_note",
  [sym_taps] = "taps",
  [sym_tap] = "tap",
  [sym_hold] = "hold",
  [sym_slides] = "slides",
  [sym_slide] = "slide",
  [sym_touch] = "touch",
  [sym_touchHold] = "touchHold",
  [sym_shape] = "shape",
  [sym_decorationTap] = "decorationTap",
  [sym_decorationHold] = "decorationHold",
  [sym_decorationStar] = "decorationStar",
  [sym_decorationSlide] = "decorationSlide",
  [sym_decorationTouch] = "decorationTouch",
  [sym_setFakeStar] = "setFakeStar",
  [sym_setNoStar] = "setNoStar",
  [sym_duration] = "duration",
  [sym_durationDelay] = "durationDelay",
  [sym_measure] = "measure",
  [sym_length] = "length",
  [sym__button] = "_button",
  [sym__sensor] = "_sensor",
  [sym_setBpm] = "setBpm",
  [sym_setDenominator] = "setDenominator",
  [sym_bpm] = "bpm",
  [sym__denominator] = "_denominator",
  [aux_sym__num] = "_num",
  [sym__decimal] = "_decimal",
  [sym__digit] = "_digit",
  [sym_end] = "end",
  [aux_sym_inote_repeat1] = "inote_repeat1",
  [aux_sym_division_repeat1] = "division_repeat1",
  [aux_sym_pseudo_repeat1] = "pseudo_repeat1",
  [aux_sym_taps_repeat1] = "taps_repeat1",
  [aux_sym_tap_repeat1] = "tap_repeat1",
  [aux_sym_hold_repeat1] = "hold_repeat1",
  [aux_sym_slides_repeat1] = "slides_repeat1",
  [aux_sym_slides_repeat2] = "slides_repeat2",
  [aux_sym_slide_repeat1] = "slide_repeat1",
  [aux_sym_slide_repeat2] = "slide_repeat2",
  [aux_sym_touchHold_repeat1] = "touchHold_repeat1",
  [aux_sym__decimal_repeat1] = "_decimal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_h] = anon_sym_h,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_v] = anon_sym_v,
  [anon_sym_p] = anon_sym_p,
  [anon_sym_q] = anon_sym_q,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_z] = anon_sym_z,
  [anon_sym_pp] = anon_sym_pp,
  [anon_sym_qq] = anon_sym_qq,
  [anon_sym_V] = anon_sym_V,
  [anon_sym_w] = anon_sym_w,
  [sym_setBreak] = sym_setBreak,
  [sym_setEx] = sym_setEx,
  [sym_setFirework] = sym_setFirework,
  [anon_sym_DOLLAR_DOLLAR] = anon_sym_DOLLAR_DOLLAR,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_setFakeTap] = sym_setFakeTap,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_A] = anon_sym_A,
  [anon_sym_B] = anon_sym_B,
  [anon_sym_D] = anon_sym_D,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_C] = anon_sym_C,
  [anon_sym_C1] = anon_sym_C1,
  [anon_sym_C2] = anon_sym_C2,
  [sym__position] = sym__position,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_1] = anon_sym_1,
  [anon_sym_2] = anon_sym_2,
  [anon_sym_3] = anon_sym_3,
  [anon_sym_4] = anon_sym_4,
  [anon_sym_5] = anon_sym_5,
  [anon_sym_6] = anon_sym_6,
  [anon_sym_7] = anon_sym_7,
  [anon_sym_8] = anon_sym_8,
  [anon_sym_9] = anon_sym_9,
  [sym_inote] = sym_inote,
  [sym_division] = sym_division,
  [sym_pseudo] = sym_pseudo,
  [sym__note] = sym__note,
  [sym_taps] = sym_taps,
  [sym_tap] = sym_tap,
  [sym_hold] = sym_hold,
  [sym_slides] = sym_slides,
  [sym_slide] = sym_slide,
  [sym_touch] = sym_touch,
  [sym_touchHold] = sym_touchHold,
  [sym_shape] = sym_shape,
  [sym_decorationTap] = sym_decorationTap,
  [sym_decorationHold] = sym_decorationHold,
  [sym_decorationStar] = sym_decorationStar,
  [sym_decorationSlide] = sym_decorationSlide,
  [sym_decorationTouch] = sym_decorationTouch,
  [sym_setFakeStar] = sym_setFakeStar,
  [sym_setNoStar] = sym_setNoStar,
  [sym_duration] = sym_duration,
  [sym_durationDelay] = sym_durationDelay,
  [sym_measure] = sym_measure,
  [sym_length] = sym_length,
  [sym__button] = sym__button,
  [sym__sensor] = sym__sensor,
  [sym_setBpm] = sym_setBpm,
  [sym_setDenominator] = sym_setDenominator,
  [sym_bpm] = sym_bpm,
  [sym__denominator] = sym__denominator,
  [aux_sym__num] = aux_sym__num,
  [sym__decimal] = sym__decimal,
  [sym__digit] = sym__digit,
  [sym_end] = sym_end,
  [aux_sym_inote_repeat1] = aux_sym_inote_repeat1,
  [aux_sym_division_repeat1] = aux_sym_division_repeat1,
  [aux_sym_pseudo_repeat1] = aux_sym_pseudo_repeat1,
  [aux_sym_taps_repeat1] = aux_sym_taps_repeat1,
  [aux_sym_tap_repeat1] = aux_sym_tap_repeat1,
  [aux_sym_hold_repeat1] = aux_sym_hold_repeat1,
  [aux_sym_slides_repeat1] = aux_sym_slides_repeat1,
  [aux_sym_slides_repeat2] = aux_sym_slides_repeat2,
  [aux_sym_slide_repeat1] = aux_sym_slide_repeat1,
  [aux_sym_slide_repeat2] = aux_sym_slide_repeat2,
  [aux_sym_touchHold_repeat1] = aux_sym_touchHold_repeat1,
  [aux_sym__decimal_repeat1] = aux_sym__decimal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_h] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_v] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_p] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_q] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_z] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_qq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_V] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_w] = {
    .visible = true,
    .named = false,
  },
  [sym_setBreak] = {
    .visible = true,
    .named = true,
  },
  [sym_setEx] = {
    .visible = true,
    .named = true,
  },
  [sym_setFirework] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_setFakeTap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_A] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_B] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_D] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_C] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_C1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_C2] = {
    .visible = true,
    .named = false,
  },
  [sym__position] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_5] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_6] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_7] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_9] = {
    .visible = true,
    .named = false,
  },
  [sym_inote] = {
    .visible = true,
    .named = true,
  },
  [sym_division] = {
    .visible = true,
    .named = true,
  },
  [sym_pseudo] = {
    .visible = true,
    .named = true,
  },
  [sym__note] = {
    .visible = false,
    .named = true,
  },
  [sym_taps] = {
    .visible = true,
    .named = true,
  },
  [sym_tap] = {
    .visible = true,
    .named = true,
  },
  [sym_hold] = {
    .visible = true,
    .named = true,
  },
  [sym_slides] = {
    .visible = true,
    .named = true,
  },
  [sym_slide] = {
    .visible = true,
    .named = true,
  },
  [sym_touch] = {
    .visible = true,
    .named = true,
  },
  [sym_touchHold] = {
    .visible = true,
    .named = true,
  },
  [sym_shape] = {
    .visible = true,
    .named = true,
  },
  [sym_decorationTap] = {
    .visible = true,
    .named = true,
  },
  [sym_decorationHold] = {
    .visible = true,
    .named = true,
  },
  [sym_decorationStar] = {
    .visible = true,
    .named = true,
  },
  [sym_decorationSlide] = {
    .visible = true,
    .named = true,
  },
  [sym_decorationTouch] = {
    .visible = true,
    .named = true,
  },
  [sym_setFakeStar] = {
    .visible = true,
    .named = true,
  },
  [sym_setNoStar] = {
    .visible = true,
    .named = true,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_durationDelay] = {
    .visible = true,
    .named = true,
  },
  [sym_measure] = {
    .visible = true,
    .named = true,
  },
  [sym_length] = {
    .visible = true,
    .named = true,
  },
  [sym__button] = {
    .visible = false,
    .named = true,
  },
  [sym__sensor] = {
    .visible = false,
    .named = true,
  },
  [sym_setBpm] = {
    .visible = true,
    .named = true,
  },
  [sym_setDenominator] = {
    .visible = true,
    .named = true,
  },
  [sym_bpm] = {
    .visible = true,
    .named = true,
  },
  [sym__denominator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__num] = {
    .visible = false,
    .named = false,
  },
  [sym__decimal] = {
    .visible = false,
    .named = true,
  },
  [sym__digit] = {
    .visible = false,
    .named = true,
  },
  [sym_end] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_inote_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_division_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pseudo_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_taps_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tap_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hold_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slides_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slides_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slide_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_slide_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_touchHold_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__decimal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '!') ADVANCE(29);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '$') ADVANCE(26);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == ',') ADVANCE(5);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '0') ADVANCE(48);
      if (lookahead == '1') ADVANCE(49);
      if (lookahead == '2') ADVANCE(50);
      if (lookahead == '3') ADVANCE(51);
      if (lookahead == '4') ADVANCE(52);
      if (lookahead == '5') ADVANCE(53);
      if (lookahead == '6') ADVANCE(54);
      if (lookahead == '7') ADVANCE(55);
      if (lookahead == '8') ADVANCE(56);
      if (lookahead == '9') ADVANCE(57);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == '<') ADVANCE(12);
      if (lookahead == '>') ADVANCE(11);
      if (lookahead == '?') ADVANCE(28);
      if (lookahead == '@') ADVANCE(27);
      if (lookahead == 'A') ADVANCE(35);
      if (lookahead == 'B') ADVANCE(36);
      if (lookahead == 'C') ADVANCE(39);
      if (lookahead == 'D') ADVANCE(37);
      if (lookahead == 'E') ADVANCE(38);
      if (lookahead == 'V') ADVANCE(20);
      if (lookahead == '[') ADVANCE(30);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == '^') ADVANCE(10);
      if (lookahead == '`') ADVANCE(4);
      if (lookahead == 'b') ADVANCE(22);
      if (lookahead == 'f') ADVANCE(24);
      if (lookahead == 'h') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(14);
      if (lookahead == 'q') ADVANCE(15);
      if (lookahead == 's') ADVANCE(16);
      if (lookahead == 'v') ADVANCE(13);
      if (lookahead == 'w') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(23);
      if (lookahead == 'z') ADVANCE(17);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '}') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '.') ADVANCE(47);
      if (lookahead == '0') ADVANCE(48);
      if (lookahead == '1') ADVANCE(49);
      if (lookahead == '2') ADVANCE(50);
      if (lookahead == '3') ADVANCE(51);
      if (lookahead == '4') ADVANCE(52);
      if (lookahead == '5') ADVANCE(53);
      if (lookahead == '6') ADVANCE(54);
      if (lookahead == '7') ADVANCE(55);
      if (lookahead == '8') ADVANCE(56);
      if (lookahead == '9') ADVANCE(57);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == '}') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '!') ADVANCE(29);
      if (lookahead == '$') ADVANCE(26);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ',') ADVANCE(5);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '/') ADVANCE(6);
      if (('1' <= lookahead && lookahead <= '8')) ADVANCE(42);
      if (lookahead == '<') ADVANCE(12);
      if (lookahead == '>') ADVANCE(11);
      if (lookahead == '?') ADVANCE(28);
      if (lookahead == '@') ADVANCE(27);
      if (lookahead == 'A') ADVANCE(35);
      if (lookahead == 'B') ADVANCE(36);
      if (lookahead == 'C') ADVANCE(39);
      if (lookahead == 'D') ADVANCE(37);
      if (lookahead == 'E') ADVANCE(38);
      if (lookahead == 'V') ADVANCE(20);
      if (lookahead == '^') ADVANCE(10);
      if (lookahead == '`') ADVANCE(4);
      if (lookahead == 'b') ADVANCE(22);
      if (lookahead == 'h') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(14);
      if (lookahead == 'q') ADVANCE(15);
      if (lookahead == 's') ADVANCE(16);
      if (lookahead == 'v') ADVANCE(13);
      if (lookahead == 'w') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(23);
      if (lookahead == 'z') ADVANCE(17);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_h);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_v);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_p);
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_q);
      if (lookahead == 'q') ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_z);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_pp);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_qq);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_V);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_w);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_setBreak);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_setEx);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_setFirework);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DOLLAR_DOLLAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '$') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_setFakeTap);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_A);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_B);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_D);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_C);
      if (lookahead == '1') ADVANCE(40);
      if (lookahead == '2') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_C1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_C2);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__position);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_1);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_2);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_3);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_4);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_5);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_6);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_7);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_8);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_9);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 2},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 2},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 2},
  [129] = {.lex_state = 2},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 2},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 2},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 2},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_h] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_v] = ACTIONS(1),
    [anon_sym_p] = ACTIONS(1),
    [anon_sym_q] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_z] = ACTIONS(1),
    [anon_sym_pp] = ACTIONS(1),
    [anon_sym_qq] = ACTIONS(1),
    [anon_sym_V] = ACTIONS(1),
    [anon_sym_w] = ACTIONS(1),
    [sym_setBreak] = ACTIONS(1),
    [sym_setEx] = ACTIONS(1),
    [sym_setFirework] = ACTIONS(1),
    [anon_sym_DOLLAR_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_setFakeTap] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_A] = ACTIONS(1),
    [anon_sym_B] = ACTIONS(1),
    [anon_sym_D] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_C] = ACTIONS(1),
    [anon_sym_C1] = ACTIONS(1),
    [anon_sym_C2] = ACTIONS(1),
    [sym__position] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_1] = ACTIONS(1),
    [anon_sym_2] = ACTIONS(1),
    [anon_sym_3] = ACTIONS(1),
    [anon_sym_4] = ACTIONS(1),
    [anon_sym_5] = ACTIONS(1),
    [anon_sym_6] = ACTIONS(1),
    [anon_sym_7] = ACTIONS(1),
    [anon_sym_8] = ACTIONS(1),
    [anon_sym_9] = ACTIONS(1),
  },
  [1] = {
    [sym_inote] = STATE(126),
    [sym_setBpm] = STATE(117),
    [anon_sym_LPAREN] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(7), 1,
      anon_sym_h,
    ACTIONS(13), 1,
      anon_sym_V,
    ACTIONS(17), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    ACTIONS(21), 1,
      sym_setFakeTap,
    STATE(16), 1,
      sym_setNoStar,
    STATE(69), 1,
      sym_setFakeStar,
    STATE(92), 1,
      sym_slide,
    STATE(143), 1,
      sym_shape,
    ACTIONS(11), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(15), 2,
      sym_setBreak,
      sym_setEx,
    ACTIONS(23), 2,
      anon_sym_QMARK,
      anon_sym_BANG,
    STATE(7), 2,
      sym_decorationStar,
      aux_sym_slides_repeat1,
    STATE(60), 2,
      sym_decorationTap,
      aux_sym_tap_repeat1,
    STATE(87), 2,
      sym_decorationHold,
      aux_sym_hold_repeat1,
    ACTIONS(5), 4,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      sym__position,
    ACTIONS(9), 10,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_w,
  [70] = 17,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_COMMA,
    ACTIONS(29), 1,
      anon_sym_E,
    ACTIONS(31), 1,
      anon_sym_C,
    ACTIONS(35), 1,
      sym__position,
    ACTIONS(37), 1,
      anon_sym_LBRACE,
    STATE(2), 1,
      sym__button,
    STATE(8), 1,
      sym_setBpm,
    STATE(11), 1,
      sym_setDenominator,
    STATE(71), 1,
      sym__sensor,
    STATE(75), 1,
      aux_sym_taps_repeat1,
    STATE(101), 1,
      sym_pseudo,
    STATE(136), 1,
      sym_end,
    ACTIONS(33), 2,
      anon_sym_C1,
      anon_sym_C2,
    STATE(4), 2,
      sym_division,
      aux_sym_inote_repeat1,
    ACTIONS(27), 3,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
    STATE(98), 7,
      sym__note,
      sym_taps,
      sym_tap,
      sym_hold,
      sym_slides,
      sym_touch,
      sym_touchHold,
  [132] = 17,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_COMMA,
    ACTIONS(29), 1,
      anon_sym_E,
    ACTIONS(31), 1,
      anon_sym_C,
    ACTIONS(35), 1,
      sym__position,
    ACTIONS(37), 1,
      anon_sym_LBRACE,
    STATE(2), 1,
      sym__button,
    STATE(8), 1,
      sym_setBpm,
    STATE(11), 1,
      sym_setDenominator,
    STATE(71), 1,
      sym__sensor,
    STATE(75), 1,
      aux_sym_taps_repeat1,
    STATE(101), 1,
      sym_pseudo,
    STATE(147), 1,
      sym_end,
    ACTIONS(33), 2,
      anon_sym_C1,
      anon_sym_C2,
    STATE(5), 2,
      sym_division,
      aux_sym_inote_repeat1,
    ACTIONS(27), 3,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
    STATE(98), 7,
      sym__note,
      sym_taps,
      sym_tap,
      sym_hold,
      sym_slides,
      sym_touch,
      sym_touchHold,
  [194] = 15,
    ACTIONS(39), 1,
      anon_sym_COMMA,
    ACTIONS(45), 1,
      anon_sym_C,
    ACTIONS(51), 1,
      sym__position,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    STATE(2), 1,
      sym__button,
    STATE(8), 1,
      sym_setBpm,
    STATE(11), 1,
      sym_setDenominator,
    STATE(71), 1,
      sym__sensor,
    STATE(75), 1,
      aux_sym_taps_repeat1,
    STATE(101), 1,
      sym_pseudo,
    ACTIONS(48), 2,
      anon_sym_C1,
      anon_sym_C2,
    STATE(5), 2,
      sym_division,
      aux_sym_inote_repeat1,
    ACTIONS(42), 4,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
    STATE(98), 7,
      sym__note,
      sym_taps,
      sym_tap,
      sym_hold,
      sym_slides,
      sym_touch,
      sym_touchHold,
  [251] = 6,
    ACTIONS(62), 1,
      anon_sym_h,
    ACTIONS(72), 1,
      anon_sym_DOLLAR,
    ACTIONS(66), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(68), 2,
      sym_setBreak,
      sym_setEx,
    ACTIONS(60), 4,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(64), 14,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
      sym_setFakeTap,
      anon_sym_QMARK,
      anon_sym_BANG,
  [288] = 9,
    ACTIONS(13), 1,
      anon_sym_V,
    STATE(16), 1,
      sym_setNoStar,
    STATE(80), 1,
      sym_slide,
    STATE(143), 1,
      sym_shape,
    ACTIONS(11), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(23), 2,
      anon_sym_QMARK,
      anon_sym_BANG,
    STATE(10), 2,
      sym_decorationStar,
      aux_sym_slides_repeat1,
    ACTIONS(21), 3,
      sym_setBreak,
      sym_setEx,
      sym_setFakeTap,
    ACTIONS(9), 10,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_w,
  [330] = 12,
    ACTIONS(31), 1,
      anon_sym_C,
    ACTIONS(35), 1,
      sym__position,
    ACTIONS(37), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(2), 1,
      sym__button,
    STATE(12), 1,
      sym_setDenominator,
    STATE(71), 1,
      sym__sensor,
    STATE(75), 1,
      aux_sym_taps_repeat1,
    STATE(107), 1,
      sym_pseudo,
    ACTIONS(33), 2,
      anon_sym_C1,
      anon_sym_C2,
    ACTIONS(27), 4,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
    STATE(98), 7,
      sym__note,
      sym_taps,
      sym_tap,
      sym_hold,
      sym_slides,
      sym_touch,
      sym_touchHold,
  [377] = 8,
    ACTIONS(13), 1,
      anon_sym_V,
    ACTIONS(78), 1,
      sym_setBreak,
    STATE(13), 1,
      aux_sym_slide_repeat2,
    STATE(95), 1,
      sym_decorationSlide,
    STATE(132), 1,
      sym_shape,
    ACTIONS(11), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(76), 4,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
    ACTIONS(9), 10,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_w,
  [415] = 6,
    STATE(16), 1,
      sym_setNoStar,
    ACTIONS(82), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(87), 2,
      anon_sym_QMARK,
      anon_sym_BANG,
    STATE(10), 2,
      sym_decorationStar,
      aux_sym_slides_repeat1,
    ACTIONS(84), 3,
      sym_setBreak,
      sym_setEx,
      sym_setFakeTap,
    ACTIONS(80), 11,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
  [449] = 10,
    ACTIONS(31), 1,
      anon_sym_C,
    ACTIONS(35), 1,
      sym__position,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(2), 1,
      sym__button,
    STATE(71), 1,
      sym__sensor,
    STATE(75), 1,
      aux_sym_taps_repeat1,
    STATE(107), 1,
      sym_pseudo,
    ACTIONS(33), 2,
      anon_sym_C1,
      anon_sym_C2,
    ACTIONS(27), 4,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
    STATE(98), 7,
      sym__note,
      sym_taps,
      sym_tap,
      sym_hold,
      sym_slides,
      sym_touch,
      sym_touchHold,
  [490] = 10,
    ACTIONS(31), 1,
      anon_sym_C,
    ACTIONS(35), 1,
      sym__position,
    ACTIONS(90), 1,
      anon_sym_COMMA,
    STATE(2), 1,
      sym__button,
    STATE(71), 1,
      sym__sensor,
    STATE(75), 1,
      aux_sym_taps_repeat1,
    STATE(114), 1,
      sym_pseudo,
    ACTIONS(33), 2,
      anon_sym_C1,
      anon_sym_C2,
    ACTIONS(27), 4,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
    STATE(98), 7,
      sym__note,
      sym_taps,
      sym_tap,
      sym_hold,
      sym_slides,
      sym_touch,
      sym_touchHold,
  [531] = 6,
    ACTIONS(100), 1,
      anon_sym_V,
    STATE(13), 1,
      aux_sym_slide_repeat2,
    STATE(132), 1,
      sym_shape,
    ACTIONS(97), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(92), 5,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      sym_setBreak,
    ACTIONS(94), 10,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_w,
  [564] = 9,
    ACTIONS(31), 1,
      anon_sym_C,
    ACTIONS(35), 1,
      sym__position,
    STATE(2), 1,
      sym__button,
    STATE(71), 1,
      sym__sensor,
    STATE(75), 1,
      aux_sym_taps_repeat1,
    STATE(118), 1,
      sym_pseudo,
    ACTIONS(33), 2,
      anon_sym_C1,
      anon_sym_C2,
    ACTIONS(27), 4,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
    STATE(98), 7,
      sym__note,
      sym_taps,
      sym_tap,
      sym_hold,
      sym_slides,
      sym_touch,
      sym_touchHold,
  [602] = 10,
    ACTIONS(103), 1,
      anon_sym_POUND,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(27), 1,
      aux_sym__decimal_repeat1,
    STATE(40), 1,
      sym__digit,
    STATE(49), 1,
      aux_sym__num,
    STATE(113), 1,
      sym__decimal,
    STATE(124), 1,
      sym_measure,
    STATE(135), 1,
      sym_length,
    STATE(142), 1,
      sym_bpm,
    ACTIONS(107), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [642] = 2,
    ACTIONS(66), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(64), 16,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
      sym_setBreak,
      sym_setEx,
      sym_setFakeTap,
      anon_sym_QMARK,
      anon_sym_BANG,
  [665] = 4,
    ACTIONS(109), 1,
      anon_sym_POUND,
    STATE(17), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    ACTIONS(111), 5,
      anon_sym_RBRACK,
      anon_sym_POUND_POUND,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DOT,
    ACTIONS(113), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [692] = 8,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(27), 1,
      aux_sym__decimal_repeat1,
    STATE(40), 1,
      sym__digit,
    STATE(49), 1,
      aux_sym__num,
    STATE(113), 1,
      sym__decimal,
    STATE(138), 1,
      sym_bpm,
    STATE(137), 2,
      sym_measure,
      sym_length,
    ACTIONS(107), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [727] = 9,
    ACTIONS(103), 1,
      anon_sym_POUND,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(27), 1,
      aux_sym__decimal_repeat1,
    STATE(40), 1,
      sym__digit,
    STATE(49), 1,
      aux_sym__num,
    STATE(119), 1,
      sym__decimal,
    STATE(131), 1,
      sym_bpm,
    STATE(145), 1,
      sym_measure,
    ACTIONS(107), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [764] = 3,
    ACTIONS(120), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(116), 5,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      sym_setBreak,
    ACTIONS(118), 11,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
  [789] = 8,
    ACTIONS(13), 1,
      anon_sym_V,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    STATE(32), 1,
      aux_sym_slide_repeat1,
    STATE(39), 1,
      sym_duration,
    STATE(73), 1,
      sym_durationDelay,
    STATE(125), 1,
      sym_shape,
    ACTIONS(11), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(9), 10,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_w,
  [824] = 2,
    ACTIONS(126), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(124), 16,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
      sym_setBreak,
  [847] = 2,
    ACTIONS(120), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(118), 16,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
      sym_setBreak,
  [870] = 2,
    ACTIONS(130), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(128), 16,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
      sym_setBreak,
      sym_setEx,
      sym_setFakeTap,
      anon_sym_QMARK,
      anon_sym_BANG,
  [893] = 8,
    ACTIONS(31), 1,
      anon_sym_C,
    ACTIONS(35), 1,
      sym__position,
    STATE(2), 1,
      sym__button,
    STATE(71), 1,
      sym__sensor,
    STATE(75), 1,
      aux_sym_taps_repeat1,
    ACTIONS(33), 2,
      anon_sym_C1,
      anon_sym_C2,
    ACTIONS(27), 4,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
    STATE(105), 7,
      sym__note,
      sym_taps,
      sym_tap,
      sym_hold,
      sym_slides,
      sym_touch,
      sym_touchHold,
  [928] = 2,
    ACTIONS(134), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(132), 16,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
      sym_setBreak,
  [951] = 5,
    ACTIONS(136), 1,
      anon_sym_POUND,
    ACTIONS(140), 1,
      anon_sym_DOT,
    STATE(17), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    ACTIONS(138), 4,
      anon_sym_RBRACK,
      anon_sym_POUND_POUND,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(142), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [980] = 9,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(27), 1,
      aux_sym__decimal_repeat1,
    STATE(40), 1,
      sym__digit,
    STATE(49), 1,
      aux_sym__num,
    STATE(113), 1,
      sym__decimal,
    STATE(123), 1,
      sym_bpm,
    STATE(134), 1,
      sym_measure,
    STATE(135), 1,
      sym_length,
    ACTIONS(107), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1017] = 3,
    ACTIONS(134), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(144), 5,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      sym_setBreak,
    ACTIONS(132), 11,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
  [1042] = 2,
    ACTIONS(148), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(146), 16,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
      sym_setBreak,
  [1065] = 4,
    ACTIONS(150), 1,
      anon_sym_POUND,
    STATE(17), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    ACTIONS(152), 4,
      anon_sym_RBRACK,
      anon_sym_POUND_POUND,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(142), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1091] = 7,
    ACTIONS(13), 1,
      anon_sym_V,
    ACTIONS(154), 1,
      anon_sym_LBRACK,
    STATE(37), 1,
      aux_sym_slide_repeat1,
    STATE(72), 1,
      sym_durationDelay,
    STATE(125), 1,
      sym_shape,
    ACTIONS(11), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(9), 10,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_w,
  [1123] = 7,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(27), 1,
      aux_sym__decimal_repeat1,
    STATE(40), 1,
      sym__digit,
    STATE(49), 1,
      aux_sym__num,
    STATE(120), 1,
      sym__decimal,
    STATE(137), 2,
      sym_measure,
      sym_length,
    ACTIONS(107), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1155] = 8,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(27), 1,
      aux_sym__decimal_repeat1,
    STATE(40), 1,
      sym__digit,
    STATE(49), 1,
      aux_sym__num,
    STATE(120), 1,
      sym__decimal,
    STATE(137), 1,
      sym_length,
    STATE(139), 1,
      sym_measure,
    ACTIONS(107), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1189] = 4,
    ACTIONS(150), 1,
      anon_sym_POUND,
    STATE(36), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    ACTIONS(152), 4,
      anon_sym_RBRACK,
      anon_sym_POUND_POUND,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(156), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1215] = 4,
    ACTIONS(158), 1,
      anon_sym_POUND,
    STATE(17), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    ACTIONS(160), 4,
      anon_sym_RBRACK,
      anon_sym_POUND_POUND,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(142), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1241] = 6,
    ACTIONS(168), 1,
      anon_sym_V,
    ACTIONS(171), 1,
      anon_sym_LBRACK,
    STATE(37), 1,
      aux_sym_slide_repeat1,
    STATE(125), 1,
      sym_shape,
    ACTIONS(165), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(162), 10,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_w,
  [1270] = 6,
    ACTIONS(105), 1,
      anon_sym_DOT,
    ACTIONS(173), 1,
      anon_sym_POUND,
    STATE(119), 1,
      sym__decimal,
    STATE(144), 1,
      sym_bpm,
    STATE(27), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    ACTIONS(175), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1299] = 5,
    ACTIONS(13), 1,
      anon_sym_V,
    STATE(9), 1,
      aux_sym_slide_repeat2,
    STATE(132), 1,
      sym_shape,
    ACTIONS(11), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(9), 10,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_w,
  [1325] = 4,
    ACTIONS(177), 1,
      anon_sym_POUND,
    ACTIONS(181), 1,
      anon_sym_COLON,
    ACTIONS(179), 3,
      anon_sym_RBRACK,
      anon_sym_POUND_POUND,
      anon_sym_DOT,
    ACTIONS(183), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1349] = 5,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(120), 1,
      sym__decimal,
    STATE(133), 1,
      sym_length,
    STATE(27), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    ACTIONS(175), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1375] = 4,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(27), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    STATE(130), 2,
      sym__denominator,
      sym__decimal,
    ACTIONS(175), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1399] = 5,
    ACTIONS(105), 1,
      anon_sym_DOT,
    STATE(120), 1,
      sym__decimal,
    STATE(140), 1,
      sym_length,
    STATE(27), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    ACTIONS(175), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1425] = 5,
    ACTIONS(13), 1,
      anon_sym_V,
    STATE(96), 1,
      sym_slide,
    STATE(143), 1,
      sym_shape,
    ACTIONS(11), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(9), 10,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_w,
  [1451] = 2,
    ACTIONS(186), 2,
      anon_sym_p,
      anon_sym_q,
    ACTIONS(171), 12,
      anon_sym_DASH,
      anon_sym_CARET,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_v,
      anon_sym_s,
      anon_sym_z,
      anon_sym_pp,
      anon_sym_qq,
      anon_sym_V,
      anon_sym_w,
      anon_sym_LBRACK,
  [1470] = 3,
    ACTIONS(188), 2,
      anon_sym_RBRACK,
      anon_sym_COLON,
    STATE(46), 2,
      aux_sym__num,
      sym__digit,
    ACTIONS(190), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1491] = 3,
    STATE(127), 1,
      sym_measure,
    STATE(49), 2,
      aux_sym__num,
      sym__digit,
    ACTIONS(193), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1511] = 3,
    ACTIONS(195), 1,
      anon_sym_RBRACK,
    STATE(46), 2,
      aux_sym__num,
      sym__digit,
    ACTIONS(197), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1531] = 3,
    ACTIONS(199), 1,
      anon_sym_COLON,
    STATE(46), 2,
      aux_sym__num,
      sym__digit,
    ACTIONS(197), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1551] = 3,
    STATE(146), 1,
      sym_measure,
    STATE(49), 2,
      aux_sym__num,
      sym__digit,
    ACTIONS(193), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1571] = 2,
    STATE(48), 2,
      aux_sym__num,
      sym__digit,
    ACTIONS(201), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1588] = 2,
    STATE(31), 2,
      sym__digit,
      aux_sym__decimal_repeat1,
    ACTIONS(203), 10,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [1605] = 2,
    ACTIONS(207), 1,
      anon_sym_C,
    ACTIONS(205), 10,
      anon_sym_COMMA,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
      anon_sym_C1,
      anon_sym_C2,
      sym__position,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1621] = 2,
    ACTIONS(211), 1,
      anon_sym_C,
    ACTIONS(209), 10,
      anon_sym_COMMA,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
      anon_sym_C1,
      anon_sym_C2,
      sym__position,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1637] = 2,
    ACTIONS(215), 1,
      anon_sym_C,
    ACTIONS(213), 10,
      anon_sym_COMMA,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
      anon_sym_C1,
      anon_sym_C2,
      sym__position,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1653] = 2,
    ACTIONS(219), 1,
      anon_sym_C,
    ACTIONS(217), 10,
      anon_sym_COMMA,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
      anon_sym_C1,
      anon_sym_C2,
      sym__position,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1669] = 2,
    ACTIONS(223), 1,
      anon_sym_C,
    ACTIONS(221), 10,
      anon_sym_COMMA,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
      anon_sym_C1,
      anon_sym_C2,
      sym__position,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1685] = 2,
    ACTIONS(227), 1,
      anon_sym_C,
    ACTIONS(225), 10,
      anon_sym_COMMA,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
      anon_sym_C1,
      anon_sym_C2,
      sym__position,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1701] = 6,
    ACTIONS(234), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(237), 1,
      anon_sym_DOLLAR,
    STATE(69), 1,
      sym_setFakeStar,
    ACTIONS(231), 2,
      sym_setBreak,
      sym_setEx,
    STATE(59), 2,
      sym_decorationTap,
      aux_sym_tap_repeat1,
    ACTIONS(229), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1724] = 6,
    ACTIONS(17), 1,
      anon_sym_DOLLAR_DOLLAR,
    ACTIONS(19), 1,
      anon_sym_DOLLAR,
    STATE(69), 1,
      sym_setFakeStar,
    ACTIONS(242), 2,
      sym_setBreak,
      sym_setEx,
    STATE(59), 2,
      sym_decorationTap,
      aux_sym_tap_repeat1,
    ACTIONS(240), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1747] = 2,
    ACTIONS(246), 1,
      anon_sym_C,
    ACTIONS(244), 9,
      anon_sym_COMMA,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
      anon_sym_C1,
      anon_sym_C2,
      sym__position,
      anon_sym_LBRACE,
  [1762] = 2,
    ACTIONS(250), 1,
      anon_sym_C,
    ACTIONS(248), 9,
      anon_sym_COMMA,
      anon_sym_A,
      anon_sym_B,
      anon_sym_D,
      anon_sym_E,
      anon_sym_C1,
      anon_sym_C2,
      sym__position,
      anon_sym_LBRACE,
  [1777] = 3,
    ACTIONS(254), 2,
      sym_setBreak,
      sym_setEx,
    STATE(63), 2,
      sym_decorationHold,
      aux_sym_hold_repeat1,
    ACTIONS(252), 5,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_h,
      anon_sym_LBRACK,
  [1793] = 5,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
    STATE(111), 1,
      sym_duration,
    ACTIONS(259), 2,
      sym_setBreak,
      sym_setEx,
    STATE(63), 2,
      sym_decorationHold,
      aux_sym_hold_repeat1,
    ACTIONS(257), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1813] = 5,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
    STATE(106), 1,
      sym_duration,
    ACTIONS(259), 2,
      sym_setBreak,
      sym_setEx,
    STATE(67), 2,
      sym_decorationHold,
      aux_sym_hold_repeat1,
    ACTIONS(263), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1833] = 5,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
    STATE(115), 1,
      sym_duration,
    ACTIONS(259), 2,
      sym_setBreak,
      sym_setEx,
    STATE(64), 2,
      sym_decorationHold,
      aux_sym_hold_repeat1,
    ACTIONS(265), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1853] = 5,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
    STATE(115), 1,
      sym_duration,
    ACTIONS(259), 2,
      sym_setBreak,
      sym_setEx,
    STATE(63), 2,
      sym_decorationHold,
      aux_sym_hold_repeat1,
    ACTIONS(265), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1873] = 2,
    ACTIONS(269), 1,
      anon_sym_DOLLAR,
    ACTIONS(267), 6,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      sym_setBreak,
      sym_setEx,
      anon_sym_DOLLAR_DOLLAR,
  [1885] = 2,
    ACTIONS(72), 1,
      anon_sym_DOLLAR,
    ACTIONS(60), 6,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      sym_setBreak,
      sym_setEx,
      anon_sym_DOLLAR_DOLLAR,
  [1897] = 1,
    ACTIONS(62), 7,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_h,
      sym_setBreak,
      sym_setEx,
      anon_sym_LBRACK,
  [1907] = 5,
    ACTIONS(273), 1,
      anon_sym_h,
    ACTIONS(275), 1,
      sym_setFirework,
    STATE(77), 1,
      sym_decorationTouch,
    STATE(97), 1,
      aux_sym_touchHold_repeat1,
    ACTIONS(271), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1925] = 3,
    ACTIONS(78), 1,
      sym_setBreak,
    STATE(95), 1,
      sym_decorationSlide,
    ACTIONS(76), 4,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
  [1938] = 3,
    ACTIONS(78), 1,
      sym_setBreak,
    STATE(100), 1,
      sym_decorationSlide,
    ACTIONS(277), 4,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
  [1951] = 1,
    ACTIONS(279), 6,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_h,
      sym_setFirework,
      anon_sym_LBRACK,
  [1960] = 3,
    ACTIONS(283), 1,
      sym__position,
    STATE(76), 2,
      sym__button,
      aux_sym_taps_repeat1,
    ACTIONS(281), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1973] = 3,
    ACTIONS(287), 1,
      sym__position,
    STATE(76), 2,
      sym__button,
      aux_sym_taps_repeat1,
    ACTIONS(285), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1986] = 2,
    ACTIONS(292), 2,
      anon_sym_h,
      sym_setFirework,
    ACTIONS(290), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [1996] = 3,
    ACTIONS(296), 1,
      anon_sym_STAR,
    STATE(91), 1,
      aux_sym_slides_repeat2,
    ACTIONS(294), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2008] = 3,
    ACTIONS(296), 1,
      anon_sym_STAR,
    STATE(91), 1,
      aux_sym_slides_repeat2,
    ACTIONS(298), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2020] = 3,
    ACTIONS(296), 1,
      anon_sym_STAR,
    STATE(78), 1,
      aux_sym_slides_repeat2,
    ACTIONS(298), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2032] = 4,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      sym_setFirework,
    STATE(102), 1,
      sym_duration,
    STATE(83), 2,
      sym_decorationTouch,
      aux_sym_touchHold_repeat1,
  [2046] = 4,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      sym_setFirework,
    STATE(110), 1,
      sym_duration,
    STATE(85), 2,
      sym_decorationTouch,
      aux_sym_touchHold_repeat1,
  [2060] = 4,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      sym_setFirework,
    STATE(108), 1,
      sym_duration,
    STATE(85), 2,
      sym_decorationTouch,
      aux_sym_touchHold_repeat1,
  [2074] = 4,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      sym_setFirework,
    STATE(108), 1,
      sym_duration,
    STATE(82), 2,
      sym_decorationTouch,
      aux_sym_touchHold_repeat1,
  [2088] = 3,
    ACTIONS(302), 1,
      sym_setFirework,
    ACTIONS(300), 2,
      anon_sym_h,
      anon_sym_LBRACK,
    STATE(85), 2,
      sym_decorationTouch,
      aux_sym_touchHold_repeat1,
  [2100] = 1,
    ACTIONS(305), 5,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      sym_setBreak,
  [2108] = 3,
    ACTIONS(307), 1,
      anon_sym_h,
    ACTIONS(259), 2,
      sym_setBreak,
      sym_setEx,
    STATE(63), 2,
      sym_decorationHold,
      aux_sym_hold_repeat1,
  [2120] = 1,
    ACTIONS(144), 5,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      sym_setBreak,
  [2128] = 1,
    ACTIONS(116), 5,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
      sym_setBreak,
  [2136] = 1,
    ACTIONS(309), 5,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_h,
      sym_setFirework,
  [2144] = 3,
    ACTIONS(313), 1,
      anon_sym_STAR,
    STATE(91), 1,
      aux_sym_slides_repeat2,
    ACTIONS(311), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2156] = 3,
    ACTIONS(296), 1,
      anon_sym_STAR,
    STATE(79), 1,
      aux_sym_slides_repeat2,
    ACTIONS(316), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2168] = 1,
    ACTIONS(318), 4,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
  [2175] = 3,
    ACTIONS(322), 1,
      anon_sym_SLASH,
    STATE(99), 1,
      aux_sym_pseudo_repeat1,
    ACTIONS(320), 2,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
  [2186] = 1,
    ACTIONS(324), 4,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
  [2193] = 1,
    ACTIONS(311), 4,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
  [2200] = 3,
    ACTIONS(275), 1,
      sym_setFirework,
    ACTIONS(326), 1,
      anon_sym_h,
    STATE(85), 2,
      sym_decorationTouch,
      aux_sym_touchHold_repeat1,
  [2211] = 3,
    ACTIONS(322), 1,
      anon_sym_SLASH,
    STATE(94), 1,
      aux_sym_pseudo_repeat1,
    ACTIONS(328), 2,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
  [2222] = 3,
    ACTIONS(332), 1,
      anon_sym_SLASH,
    STATE(99), 1,
      aux_sym_pseudo_repeat1,
    ACTIONS(330), 2,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
  [2233] = 1,
    ACTIONS(76), 4,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
      anon_sym_STAR,
  [2240] = 3,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    ACTIONS(335), 1,
      anon_sym_BQUOTE,
    STATE(109), 1,
      aux_sym_division_repeat1,
  [2250] = 1,
    ACTIONS(337), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2256] = 3,
    ACTIONS(339), 1,
      anon_sym_BQUOTE,
    ACTIONS(342), 1,
      anon_sym_COMMA,
    STATE(103), 1,
      aux_sym_division_repeat1,
  [2266] = 3,
    ACTIONS(335), 1,
      anon_sym_BQUOTE,
    ACTIONS(344), 1,
      anon_sym_COMMA,
    STATE(103), 1,
      aux_sym_division_repeat1,
  [2276] = 1,
    ACTIONS(330), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2282] = 1,
    ACTIONS(265), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2288] = 3,
    ACTIONS(90), 1,
      anon_sym_COMMA,
    ACTIONS(335), 1,
      anon_sym_BQUOTE,
    STATE(112), 1,
      aux_sym_division_repeat1,
  [2298] = 1,
    ACTIONS(346), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2304] = 3,
    ACTIONS(90), 1,
      anon_sym_COMMA,
    ACTIONS(335), 1,
      anon_sym_BQUOTE,
    STATE(103), 1,
      aux_sym_division_repeat1,
  [2314] = 1,
    ACTIONS(348), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2320] = 1,
    ACTIONS(350), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2326] = 3,
    ACTIONS(335), 1,
      anon_sym_BQUOTE,
    ACTIONS(352), 1,
      anon_sym_COMMA,
    STATE(103), 1,
      aux_sym_division_repeat1,
  [2336] = 2,
    ACTIONS(354), 1,
      anon_sym_POUND,
    ACTIONS(356), 2,
      anon_sym_RBRACK,
      anon_sym_POUND_POUND,
  [2344] = 3,
    ACTIONS(335), 1,
      anon_sym_BQUOTE,
    ACTIONS(352), 1,
      anon_sym_COMMA,
    STATE(104), 1,
      aux_sym_division_repeat1,
  [2354] = 1,
    ACTIONS(257), 3,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
      anon_sym_SLASH,
  [2360] = 2,
    ACTIONS(358), 1,
      ts_builtin_sym_end,
    ACTIONS(360), 1,
      sym__position,
  [2367] = 2,
    ACTIONS(37), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_setDenominator,
  [2374] = 1,
    ACTIONS(342), 2,
      anon_sym_BQUOTE,
      anon_sym_COMMA,
  [2379] = 1,
    ACTIONS(362), 2,
      anon_sym_POUND,
      anon_sym_RPAREN,
  [2384] = 1,
    ACTIONS(356), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [2389] = 2,
    ACTIONS(261), 1,
      anon_sym_LBRACK,
    STATE(30), 1,
      sym_duration,
  [2396] = 1,
    ACTIONS(364), 1,
      sym__position,
  [2400] = 1,
    ACTIONS(366), 1,
      anon_sym_POUND,
  [2404] = 1,
    ACTIONS(368), 1,
      anon_sym_RBRACK,
  [2408] = 1,
    ACTIONS(370), 1,
      sym__position,
  [2412] = 1,
    ACTIONS(372), 1,
      ts_builtin_sym_end,
  [2416] = 1,
    ACTIONS(374), 1,
      anon_sym_RBRACK,
  [2420] = 1,
    ACTIONS(376), 1,
      sym__position,
  [2424] = 1,
    ACTIONS(360), 1,
      sym__position,
  [2428] = 1,
    ACTIONS(378), 1,
      anon_sym_RBRACE,
  [2432] = 1,
    ACTIONS(380), 1,
      anon_sym_POUND,
  [2436] = 1,
    ACTIONS(382), 1,
      sym__position,
  [2440] = 1,
    ACTIONS(384), 1,
      anon_sym_RBRACK,
  [2444] = 1,
    ACTIONS(386), 1,
      anon_sym_RBRACK,
  [2448] = 1,
    ACTIONS(388), 1,
      anon_sym_POUND_POUND,
  [2452] = 1,
    ACTIONS(390), 1,
      ts_builtin_sym_end,
  [2456] = 1,
    ACTIONS(392), 1,
      anon_sym_RBRACK,
  [2460] = 1,
    ACTIONS(394), 1,
      anon_sym_POUND,
  [2464] = 1,
    ACTIONS(396), 1,
      anon_sym_RBRACK,
  [2468] = 1,
    ACTIONS(398), 1,
      anon_sym_RPAREN,
  [2472] = 1,
    ACTIONS(400), 1,
      sym__position,
  [2476] = 1,
    ACTIONS(402), 1,
      anon_sym_POUND,
  [2480] = 1,
    ACTIONS(404), 1,
      sym__position,
  [2484] = 1,
    ACTIONS(406), 1,
      anon_sym_RPAREN,
  [2488] = 1,
    ACTIONS(408), 1,
      anon_sym_RBRACK,
  [2492] = 1,
    ACTIONS(410), 1,
      anon_sym_RBRACK,
  [2496] = 1,
    ACTIONS(412), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 70,
  [SMALL_STATE(4)] = 132,
  [SMALL_STATE(5)] = 194,
  [SMALL_STATE(6)] = 251,
  [SMALL_STATE(7)] = 288,
  [SMALL_STATE(8)] = 330,
  [SMALL_STATE(9)] = 377,
  [SMALL_STATE(10)] = 415,
  [SMALL_STATE(11)] = 449,
  [SMALL_STATE(12)] = 490,
  [SMALL_STATE(13)] = 531,
  [SMALL_STATE(14)] = 564,
  [SMALL_STATE(15)] = 602,
  [SMALL_STATE(16)] = 642,
  [SMALL_STATE(17)] = 665,
  [SMALL_STATE(18)] = 692,
  [SMALL_STATE(19)] = 727,
  [SMALL_STATE(20)] = 764,
  [SMALL_STATE(21)] = 789,
  [SMALL_STATE(22)] = 824,
  [SMALL_STATE(23)] = 847,
  [SMALL_STATE(24)] = 870,
  [SMALL_STATE(25)] = 893,
  [SMALL_STATE(26)] = 928,
  [SMALL_STATE(27)] = 951,
  [SMALL_STATE(28)] = 980,
  [SMALL_STATE(29)] = 1017,
  [SMALL_STATE(30)] = 1042,
  [SMALL_STATE(31)] = 1065,
  [SMALL_STATE(32)] = 1091,
  [SMALL_STATE(33)] = 1123,
  [SMALL_STATE(34)] = 1155,
  [SMALL_STATE(35)] = 1189,
  [SMALL_STATE(36)] = 1215,
  [SMALL_STATE(37)] = 1241,
  [SMALL_STATE(38)] = 1270,
  [SMALL_STATE(39)] = 1299,
  [SMALL_STATE(40)] = 1325,
  [SMALL_STATE(41)] = 1349,
  [SMALL_STATE(42)] = 1375,
  [SMALL_STATE(43)] = 1399,
  [SMALL_STATE(44)] = 1425,
  [SMALL_STATE(45)] = 1451,
  [SMALL_STATE(46)] = 1470,
  [SMALL_STATE(47)] = 1491,
  [SMALL_STATE(48)] = 1511,
  [SMALL_STATE(49)] = 1531,
  [SMALL_STATE(50)] = 1551,
  [SMALL_STATE(51)] = 1571,
  [SMALL_STATE(52)] = 1588,
  [SMALL_STATE(53)] = 1605,
  [SMALL_STATE(54)] = 1621,
  [SMALL_STATE(55)] = 1637,
  [SMALL_STATE(56)] = 1653,
  [SMALL_STATE(57)] = 1669,
  [SMALL_STATE(58)] = 1685,
  [SMALL_STATE(59)] = 1701,
  [SMALL_STATE(60)] = 1724,
  [SMALL_STATE(61)] = 1747,
  [SMALL_STATE(62)] = 1762,
  [SMALL_STATE(63)] = 1777,
  [SMALL_STATE(64)] = 1793,
  [SMALL_STATE(65)] = 1813,
  [SMALL_STATE(66)] = 1833,
  [SMALL_STATE(67)] = 1853,
  [SMALL_STATE(68)] = 1873,
  [SMALL_STATE(69)] = 1885,
  [SMALL_STATE(70)] = 1897,
  [SMALL_STATE(71)] = 1907,
  [SMALL_STATE(72)] = 1925,
  [SMALL_STATE(73)] = 1938,
  [SMALL_STATE(74)] = 1951,
  [SMALL_STATE(75)] = 1960,
  [SMALL_STATE(76)] = 1973,
  [SMALL_STATE(77)] = 1986,
  [SMALL_STATE(78)] = 1996,
  [SMALL_STATE(79)] = 2008,
  [SMALL_STATE(80)] = 2020,
  [SMALL_STATE(81)] = 2032,
  [SMALL_STATE(82)] = 2046,
  [SMALL_STATE(83)] = 2060,
  [SMALL_STATE(84)] = 2074,
  [SMALL_STATE(85)] = 2088,
  [SMALL_STATE(86)] = 2100,
  [SMALL_STATE(87)] = 2108,
  [SMALL_STATE(88)] = 2120,
  [SMALL_STATE(89)] = 2128,
  [SMALL_STATE(90)] = 2136,
  [SMALL_STATE(91)] = 2144,
  [SMALL_STATE(92)] = 2156,
  [SMALL_STATE(93)] = 2168,
  [SMALL_STATE(94)] = 2175,
  [SMALL_STATE(95)] = 2186,
  [SMALL_STATE(96)] = 2193,
  [SMALL_STATE(97)] = 2200,
  [SMALL_STATE(98)] = 2211,
  [SMALL_STATE(99)] = 2222,
  [SMALL_STATE(100)] = 2233,
  [SMALL_STATE(101)] = 2240,
  [SMALL_STATE(102)] = 2250,
  [SMALL_STATE(103)] = 2256,
  [SMALL_STATE(104)] = 2266,
  [SMALL_STATE(105)] = 2276,
  [SMALL_STATE(106)] = 2282,
  [SMALL_STATE(107)] = 2288,
  [SMALL_STATE(108)] = 2298,
  [SMALL_STATE(109)] = 2304,
  [SMALL_STATE(110)] = 2314,
  [SMALL_STATE(111)] = 2320,
  [SMALL_STATE(112)] = 2326,
  [SMALL_STATE(113)] = 2336,
  [SMALL_STATE(114)] = 2344,
  [SMALL_STATE(115)] = 2354,
  [SMALL_STATE(116)] = 2360,
  [SMALL_STATE(117)] = 2367,
  [SMALL_STATE(118)] = 2374,
  [SMALL_STATE(119)] = 2379,
  [SMALL_STATE(120)] = 2384,
  [SMALL_STATE(121)] = 2389,
  [SMALL_STATE(122)] = 2396,
  [SMALL_STATE(123)] = 2400,
  [SMALL_STATE(124)] = 2404,
  [SMALL_STATE(125)] = 2408,
  [SMALL_STATE(126)] = 2412,
  [SMALL_STATE(127)] = 2416,
  [SMALL_STATE(128)] = 2420,
  [SMALL_STATE(129)] = 2424,
  [SMALL_STATE(130)] = 2428,
  [SMALL_STATE(131)] = 2432,
  [SMALL_STATE(132)] = 2436,
  [SMALL_STATE(133)] = 2440,
  [SMALL_STATE(134)] = 2444,
  [SMALL_STATE(135)] = 2448,
  [SMALL_STATE(136)] = 2452,
  [SMALL_STATE(137)] = 2456,
  [SMALL_STATE(138)] = 2460,
  [SMALL_STATE(139)] = 2464,
  [SMALL_STATE(140)] = 2468,
  [SMALL_STATE(141)] = 2472,
  [SMALL_STATE(142)] = 2476,
  [SMALL_STATE(143)] = 2480,
  [SMALL_STATE(144)] = 2484,
  [SMALL_STATE(145)] = 2488,
  [SMALL_STATE(146)] = 2492,
  [SMALL_STATE(147)] = 2496,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_taps_repeat1, 1),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inote_repeat1, 2), SHIFT_REPEAT(56),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inote_repeat1, 2), SHIFT_REPEAT(129),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inote_repeat1, 2), SHIFT_REPEAT(71),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inote_repeat1, 2), SHIFT_REPEAT(71),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inote_repeat1, 2), SHIFT_REPEAT(2),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inote_repeat1, 2), SHIFT_REPEAT(38),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_inote_repeat1, 2), SHIFT_REPEAT(42),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorationTap, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorationHold, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorationStar, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorationStar, 1),
  [68] = {.entry = {.count = 3, .reusable = true}}, REDUCE(sym_decorationTap, 1), REDUCE(sym_decorationHold, 1), REDUCE(sym_decorationStar, 1),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorationTap, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slide, 4),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slides_repeat1, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_slides_repeat1, 2),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slides_repeat1, 2), SHIFT_REPEAT(16),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slides_repeat1, 2), SHIFT_REPEAT(24),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slide_repeat2, 2),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slide_repeat2, 2), SHIFT_REPEAT(122),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_slide_repeat2, 2), SHIFT_REPEAT(122),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slide_repeat2, 2), SHIFT_REPEAT(141),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__decimal_repeat1, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__decimal_repeat1, 2),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__decimal_repeat1, 2), SHIFT_REPEAT(17),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_durationDelay, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_duration, 3),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_duration, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_duration, 4),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_duration, 4),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setNoStar, 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setNoStar, 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_duration, 5),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_duration, 5),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__decimal, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_durationDelay, 5),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slide_repeat2, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_slide_repeat2, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__decimal, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__decimal, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 3),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slide_repeat1, 2), SHIFT_REPEAT(122),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_slide_repeat1, 2), SHIFT_REPEAT(122),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slide_repeat1, 2), SHIFT_REPEAT(141),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slide_repeat1, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__decimal_repeat1, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__decimal_repeat1, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__num, 1),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__num, 1), REDUCE(aux_sym__decimal_repeat1, 1),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_slide_repeat1, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__num, 2),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__num, 2), SHIFT_REPEAT(46),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_measure, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division, 4),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_division, 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division, 5),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_division, 5),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setDenominator, 3),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setDenominator, 3),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division, 1),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_division, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division, 2),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_division, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division, 3),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_division, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tap_repeat1, 2),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tap_repeat1, 2), SHIFT_REPEAT(69),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tap_repeat1, 2), SHIFT_REPEAT(68),
  [237] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tap_repeat1, 2), SHIFT_REPEAT(68),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tap, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setBpm, 3),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setBpm, 3),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setBpm, 4),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setBpm, 4),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hold_repeat1, 2),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hold_repeat1, 2), SHIFT_REPEAT(70),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hold, 4),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hold, 2),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hold, 3),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setFakeStar, 1),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setFakeStar, 1),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_touch, 1),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slide, 3),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorationTouch, 1),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_taps, 1),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_taps_repeat1, 2),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_taps_repeat1, 2), SHIFT_REPEAT(76),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_touch, 2),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_touchHold_repeat1, 1),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slides, 4),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slides, 3),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_touchHold_repeat1, 2),
  [302] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_touchHold_repeat1, 2), SHIFT_REPEAT(74),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_durationDelay, 7),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sensor, 2),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_slides_repeat2, 2),
  [313] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_slides_repeat2, 2), SHIFT_REPEAT(44),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slides, 2),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorationSlide, 1),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pseudo, 2),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slide, 5),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pseudo, 1),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pseudo_repeat1, 2),
  [332] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pseudo_repeat1, 2), SHIFT_REPEAT(25),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_touchHold, 3),
  [339] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_division_repeat1, 2), SHIFT_REPEAT(14),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_division_repeat1, 2),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_touchHold, 4),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_touchHold, 5),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hold, 5),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [354] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bpm, 1),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_length, 1),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end, 1),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bpm, 1),
  [364] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shape, 1),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [372] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [376] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shape, 2),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [390] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inote, 3),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [412] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inote, 4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_tree_sitter_simai(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
